# Generated by Django 5.0.7 on 2024-08-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
