# Generated by Django 5.0.7 on 2024-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_participation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
